/**
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 *  V3 PORT — ADAPTER NOTES
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 *
 *  Source: ..\numu-egyptian-bazaar\src\themes\street\sections\products-page\StStreetProductsPageSection.tsx
 *
 *  Generated by `numu-theme migrate`. Review and rewrite using V3
 *  SDK hooks before publishing. The list below was inferred from
 *  static analysis — there may be other V2 idioms not detected.
 *
 *  No V2-specific hooks detected. You may only need to:
 *    1. Replace any bazaar-specific imports with @numueg/theme-sdk equivalents.
 *    2. Wrap your section's root element with <Section id={...} type={...}> from the SDK.
 *    3. Read settings from `props.instance.settings` (V3 SectionInstance shape).
 *  When done, remove this block.
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 */

import type { SectionComponentProps } from "../v2-bridge";
import { BaseProductsPage } from "@/components/store/shared/BaseProductsPage";
import { StStreetProductCard } from "@/components/store/street/StStreetProductCard";

export default function StStreetProductsPageSection({ section }: SectionComponentProps) {
  const { settings } = section;

  return (
    <BaseProductsPage
      styles={{
        container: "container mx-auto px-4 py-8",
        breadcrumb: "flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-foreground/60 mb-6",
        breadcrumbActive: "text-foreground",
        pageTitle: "st-section-title mb-6",
        searchWrapper: "relative mb-6",
        searchInput: "st-input pr-10 w-full",
        searchIcon: "absolute right-4 top-1/2 -translate-y-1/2 text-muted-foreground",
        clearButton: "absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground",
        categoryContainer: "flex gap-2 overflow-x-auto pb-4 mb-6",
        categoryButton: "shrink-0 px-4 py-2 text-xs font-black uppercase tracking-wide rounded-full transition-all border-2 border-[var(--st-dark)] text-[var(--st-dark)] bg-transparent",
        categoryButtonActive: "!bg-[var(--st-dark)] !text-[var(--st-yellow)]",
        toolbar: "flex items-center justify-between mb-6",
        productCount: "text-sm font-bold text-foreground/60 uppercase tracking-widest",
        sortSelect: "st-input w-auto min-w-[130px]",
        grid: "grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4",
        emptyTitle: "text-2xl font-black uppercase tracking-wide mb-4",
        emptySubtitle: "text-sm",
        showViewToggle: settings.show_view_toggle ?? false,
        showCategorySubtitle: settings.show_category_subtitle ?? false,
      }}
      renderCard={(p) => <StStreetProductCard key={p.id} product={p} />}
    />
  );
}
