/**
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 *  V3 PORT — ADAPTER NOTES
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 *
 *  Source: ..\numu-egyptian-bazaar\src\themes\street\sections\product-detail\StStreetProductDetailSection.tsx
 *
 *  Generated by `numu-theme migrate`. Review and rewrite using V3
 *  SDK hooks before publishing. The list below was inferred from
 *  static analysis — there may be other V2 idioms not detected.
 *
 *  No V2-specific hooks detected. You may only need to:
 *    1. Replace any bazaar-specific imports with @numueg/theme-sdk equivalents.
 *    2. Wrap your section's root element with <Section id={...} type={...}> from the SDK.
 *    3. Read settings from `props.instance.settings` (V3 SectionInstance shape).
 *  When done, remove this block.
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 */

import type { SectionComponentProps } from "../v2-bridge";
import {
  BaseProductDetailPage,
  type ProductDetailStyles,
} from "@/components/store/shared/BaseProductDetailPage";
import { StStreetProductCard } from "@/components/store/street/StStreetProductCard";

const styles: ProductDetailStyles = {
  container: "container mx-auto px-4 py-4",
  gridLayout: "grid grid-cols-1 md:grid-cols-2 gap-8",
  breadcrumb:
    "flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-muted-foreground mb-4",
  breadcrumbActive: "text-foreground truncate",
  mainImage: "aspect-[4/5] overflow-hidden relative",
  thumbnailContainer:
    "flex gap-2 p-3 overflow-x-auto scrollbar-hide",
  thumbnail:
    "w-14 h-14 shrink-0 overflow-hidden rounded-lg transition-all opacity-50 hover:opacity-80",
  thumbnailActive:
    "ring-2 ring-foreground ring-offset-1 opacity-100",
  productName:
    "text-3xl md:text-5xl font-black uppercase leading-none mb-4",
  price: "text-3xl font-black",
  originalPrice: "text-lg text-foreground/50 line-through",
  description:
    "text-sm font-semibold text-foreground/70 uppercase tracking-wide leading-relaxed mb-6 max-w-xs",
  sizeLabel:
    "text-xs font-black uppercase tracking-widest mb-3 block",
  sizeButton: "st-size-btn",
  sizeButtonActive: "active",
  colorLabel:
    "text-xs font-black uppercase tracking-widest mb-3 block",
  colorButton:
    "w-8 h-8 rounded-full transition-all border-2 border-transparent",
  colorButtonActive:
    "border-[3px] border-[var(--st-dark)] outline outline-2 outline-[var(--st-dark)] outline-offset-2",
  colorSwatch: "w-full h-full rounded-full",
  quantityContainer: "mb-4",
  addToCartButton:
    "st-btn w-full py-4 text-base flex items-center justify-center gap-3 transition-all disabled:opacity-50",
  addedButton: "opacity-80",
  relatedSection: "py-12 mt-8",
  relatedTitle: "st-section-title mb-8",
  relatedGrid: "grid grid-cols-2 md:grid-cols-4 gap-4",
  showRating: false,
  showStock: false,
  showWhatsapp: false,
  showGuarantees: false,
  showTags: false,
};

export default function StStreetProductDetailSection({
  section,
}: SectionComponentProps) {
  const { settings } = section;

  return (
    <BaseProductDetailPage
      styles={{
        ...styles,
        showRating: settings.show_rating ?? false,
        showStock: settings.show_stock ?? false,
        showWhatsapp: settings.show_whatsapp ?? false,
        showGuarantees: settings.show_guarantees ?? false,
        showTags: settings.show_tags ?? false,
      }}
      renderCard={(p) => (
        <StStreetProductCard key={p.id} product={p} />
      )}
    />
  );
}
