/**
 * Street (V3) (V3) — entry point.
 *
 * Generated by `numu-theme migrate`. Section components live in
 * src/sections/<type>.tsx and are lazy-loaded so only sections the
 * merchant actually uses pay the bundle cost.
 */

import {
  StrictMode,
  lazy,
  Suspense,
  useImperativeHandle,
  useRef,
  useState,
  forwardRef,
} from "react";
import { createRoot, type Root } from "react-dom/client";
import {
  NuMuProvider,
  Section,
  useThemeSettings,
  type ThemeSettingsV3,
  type Store,
  type Cart,
  type Customer,
  type SectionInstance,
  type MountResult,
} from "@numueg/theme-sdk";
import themeManifest from "../theme.json";

const SECTION_REGISTRY: Record<string, ReturnType<typeof lazy>> = {
  "st-street-product-detail-section": lazy(() => import("./sections/st-street-product-detail-section")),
  "st-street-products-page-section": lazy(() => import("./sections/st-street-products-page-section")),
};

function UnknownSection({ type }: { type: string }) {
  return (
    <section style={{ padding: "1rem", border: "1px dashed #fb923c" }}>
      Unknown section: <strong>{type}</strong>
    </section>
  );
}

interface ResolvedSection {
  id: string;
  instance: SectionInstance;
}

interface MaybeOrdered {
  sections?: Record<string, SectionInstance> | SectionInstance[];
  order?: string[];
}

function resolveSections(group: MaybeOrdered | undefined): ResolvedSection[] {
  if (!group) return [];
  if (Array.isArray(group.sections)) {
    return group.sections.map((instance, idx) => ({
      id: `${instance.type}-${idx}`,
      instance,
    }));
  }
  const map = (group.sections ?? {}) as Record<string, SectionInstance>;
  const order = group.order ?? Object.keys(map);
  return order
    .map((id): ResolvedSection | null => {
      const instance = map[id];
      if (!instance) return null;
      return { id, instance };
    })
    .filter((x): x is ResolvedSection => Boolean(x));
}

const BUILTIN_HOME = (themeManifest as unknown as { presets?: { templates?: { home?: MaybeOrdered } } })
  .presets?.templates?.home;

function RenderSection({
  instance,
  sectionId,
  groupId,
}: {
  instance: SectionInstance;
  sectionId: string;
  groupId?: string;
}) {
  const Component = SECTION_REGISTRY[instance.type];
  if (!Component) {
    return (
      <Section id={sectionId} type={instance.type} groupId={groupId}>
        <UnknownSection type={instance.type} />
      </Section>
    );
  }
  return (
    <Section id={sectionId} type={instance.type} groupId={groupId}>
      <Suspense fallback={<div style={{ minHeight: "20vh" }} />}>
        <Component instance={instance} />
      </Suspense>
    </Section>
  );
}

function ThemeApp() {
  const settings = useThemeSettings();
  const hostHome = settings.templates?.home as MaybeOrdered | undefined;
  const sections = resolveSections(hostHome ?? BUILTIN_HOME);
  return (
    <div data-street-v3-app>
      {sections.map(({ id, instance }) => (
        <RenderSection key={id} sectionId={id} instance={instance} />
      ))}
    </div>
  );
}

// ── Host contract: mount(el, ctx) returns a MountResult ────────────────────

export interface MountContext {
  store: Store;
  themeSettings: ThemeSettingsV3;
  initialCart?: Cart;
  customer?: Customer | null;
  locale?: string;
  translations?: Record<string, string>;
  [extra: string]: unknown;
}

interface DraftHandle {
  applyDraft: (next: ThemeSettingsV3) => void;
}

const ThemeSettingsBridge = forwardRef<DraftHandle, { ctx: MountContext }>(
  function ThemeSettingsBridge({ ctx }, ref) {
    const [themeSettings, setThemeSettings] = useState<ThemeSettingsV3>(
      ctx.themeSettings,
    );
    useImperativeHandle(
      ref,
      () => ({
        applyDraft: (next) => setThemeSettings((prev) => (prev === next ? prev : next)),
      }),
      [],
    );
    return (
      <NuMuProvider
        store={ctx.store}
        themeSettings={themeSettings}
        initialCart={ctx.initialCart}
        customer={ctx.customer}
        locale={ctx.locale}
        translations={ctx.translations}
      >
        <ThemeApp />
      </NuMuProvider>
    );
  },
);

let currentRoot: Root | null = null;

export function mount(el: HTMLElement, ctx: MountContext): MountResult {
  if (currentRoot) {
    currentRoot.unmount();
    currentRoot = null;
  }
  const root = createRoot(el);
  currentRoot = root;
  const handleRef = { current: null as DraftHandle | null };
  root.render(
    <StrictMode>
      <ThemeSettingsBridge
        ctx={ctx}
        ref={(h) => {
          handleRef.current = h;
        }}
      />
    </StrictMode>,
  );
  return {
    applyDraft: (next) => handleRef.current?.applyDraft(next),
    cleanup: () => {
      root.unmount();
      if (currentRoot === root) currentRoot = null;
      handleRef.current = null;
    },
  };
}

const v3Handle = {
  kind: "v3-mount" as const,
  numu_theme_version: 3 as const,
  mount_returns: "MountResult" as const,
  manifest: { id: "street-v3", name: "Street (V3)", version: "0.1.0" },
  mount,
};
export default v3Handle;
