/**
 * Street (V3) (V3) — entry point.
 *
 * Generated by `numu-theme migrate`. Section components live in
 * src/sections/<type>.tsx and are lazy-loaded so only sections the
 * merchant actually uses pay the bundle cost.
 */

import { type ComponentType } from "react";
import {
  Section,
  useThemeSettings,
  defineThemeEntry,
  type ThemeSettingsV3,
  type Store,
  type Cart,
  type Customer,
  type SectionInstance,
} from "@numueg/theme-sdk";
import themeManifest from "../theme.json";

// Eager section imports (no React.lazy): sections bundle into theme.js so the
// page renders in one commit (no chunk-download flash); SSR-safe.
import StStreetProductDetailSection from "./sections/st-street-product-detail-section";
import StStreetProductsPageSection from "./sections/st-street-products-page-section";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const SECTION_REGISTRY: Record<string, ComponentType<any>> = {
  "st-street-product-detail-section": StStreetProductDetailSection,
  "st-street-products-page-section": StStreetProductsPageSection,
};

function UnknownSection({ type }: { type: string }) {
  return (
    <section style={{ padding: "1rem", border: "1px dashed #fb923c" }}>
      Unknown section: <strong>{type}</strong>
    </section>
  );
}

interface ResolvedSection {
  id: string;
  instance: SectionInstance;
}

interface MaybeOrdered {
  sections?: Record<string, SectionInstance> | SectionInstance[];
  order?: string[];
}

function resolveSections(group: MaybeOrdered | undefined): ResolvedSection[] {
  if (!group) return [];
  if (Array.isArray(group.sections)) {
    return group.sections.map((instance, idx) => ({
      id: `${instance.type}-${idx}`,
      instance,
    }));
  }
  const map = (group.sections ?? {}) as Record<string, SectionInstance>;
  const order = group.order ?? Object.keys(map);
  return order
    .map((id): ResolvedSection | null => {
      const instance = map[id];
      if (!instance) return null;
      return { id, instance };
    })
    .filter((x): x is ResolvedSection => Boolean(x));
}

const BUILTIN_HOME = (themeManifest as unknown as { presets?: { templates?: { home?: MaybeOrdered } } })
  .presets?.templates?.home;

function RenderSection({
  instance,
  sectionId,
  groupId,
}: {
  instance: SectionInstance;
  sectionId: string;
  groupId?: string;
}) {
  const Component = SECTION_REGISTRY[instance.type];
  if (!Component) {
    return (
      <Section id={sectionId} type={instance.type} groupId={groupId}>
        <UnknownSection type={instance.type} />
      </Section>
    );
  }
  return (
    <Section id={sectionId} type={instance.type} groupId={groupId}>
      <Component instance={instance} />
    </Section>
  );
}

function ThemeApp() {
  const settings = useThemeSettings();
  const hostHome = settings.templates?.home as MaybeOrdered | undefined;
  const sections = resolveSections(hostHome ?? BUILTIN_HOME);
  return (
    <div data-street-v3-app>
      {sections.map(({ id, instance }) => (
        <RenderSection key={id} sectionId={id} instance={instance} />
      ))}
    </div>
  );
}

// ── Host contract: mount(el, ctx) returns a MountResult ────────────────────

export interface MountContext {
  store: Store;
  themeSettings: ThemeSettingsV3;
  initialCart?: Cart;
  customer?: Customer | null;
  locale?: string;
  translations?: Record<string, string>;
  [extra: string]: unknown;
}

// defineThemeEntry yields both mount (client) and createApp (server SSR). The
// SDK's buildThemeElement handles the NuMuProvider wiring (store / themeSettings
// / cart / customer / locale) that this theme's old hand-rolled mount did.
const entry = defineThemeEntry(() => <ThemeApp />);

export const mount = entry.mount;
export const createApp = entry.createApp;

const v3Handle = {
  kind: "v3-mount" as const,
  numu_theme_version: 3 as const,
  mount_returns: "MountResult" as const,
  manifest: { id: "street-v3", name: "Street (V3)", version: "0.1.0" },
  mount,
};
export default v3Handle;
